apiVersion: v1
kind: ConfigMap
metadata:
  name: enforcer-configmap
  namespace: enforcer
data:
  openaz-pep-rest.properties: |
    nextlabs.oauth2.client_id=apiclient
    nextlabs.oauth2.client_secret=123Blue!123
    nextlabs.oauth2.server=hinako.nextlabs.com
    nextlabs.oauth2.port=57070
    nextlabs.rest.host=hinako.nextlabs.com
    nextlabs.rest.port=57070
  daemon.json: |
    {
      "insecure-registries": ["registry.nextlabs.com"]
    }