apiVersion: v1
kind: ConfigMap
metadata:
  name: enforcer-configmap
  namespace: enforcer
data:
  openaz-pep-rest.properties: |
    nextlabs.pdp.engine.name=com.nextlabs.openaz.pdp.RestPDPEngine
    nextlabs.rest.payload_content_type=application/json
    nextlabs.rest.host=db0e-118-189-171-229.ngrok-free.app
    nextlabs.rest.port=443
    nextlabs.rest.https=true
    nextlabs.rest.auth_type=OAUTH2
    nextlabs.oauth2.grant_type=client_credentials
    nextlabs.oauth2.server=db0e-118-189-171-229.ngrok-free.app
    nextlabs.oauth2.port=443
    nextlabs.oauth2.https=true
    nextlabs.oauth2.client_id=apiclient
    nextlabs.oauth2.client_secret=123Blue!123
    nextlabs.oauth2.token_endpoint_path=/dpc/oauth
    nextlabs.rest.ignore_https_certificate=true
    xacml.pdpEngineFactory=com.nextlabs.openaz.pdp.PDPEngineFactoryImpl
    pep.mapper.classes=com.nextlabs.openaz.pepapi.RecipientMapper,com.nextlabs.openaz.pepapi.DiscretionaryPoliciesMapper,com.nextlabs.openaz.pepapi.HostMapper,com.nextlabs.openaz.pepapi.ApplicationMapper
