apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt-secret
  namespace: enforcer
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  nextlabs.enforcer.jwt.key: {{ .Values.nextlabs.enforcer.jwt.key | b64enc }}