apiVersion: v1
kind: Secret
metadata:
  name: openaz-pep-secret
  namespace: enforcer
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
type: Opaque
stringData:
  nextlabs.oauth2.client_secret: 4GmcviE5w23bY6hsJfS0FY5Ty8I6RJ1OlzrjySh9jz0=