autoscaling:
  enabled: false
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
image:
  imagePullSecret: nextlabs-registry-credentials
  pullPolicy: Always
  repository: registry.nextlabs.com

# Update the pod configuration with insecureSkipTLSVerify
podConfig:
  containers:
    - name: enforcer-container
      image: "{{ .Values.repository }}:latest"  # Assuming latest tag
      imagePullSecret: "{{ .Values.imagePullSecret }}"
      env:
      - name: insecureSkipTLSVerify
        value: "true"  # Disabling TLS verification (Not Recommended)

nextlabs:
  cc:
    configService:
      password: null
    logsVolumeClaimName: null
  enforcer:
    jwt:
      key: NEdtY3ZpRTV3MjNiWTZoc0pmUzBGWTVUeThJNlJKMU9senJqeVNoOWp6MD0=
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi
securityContext:
  fsGroup: null
  runAsUser: null
service:
  type: ClusterIP
statusCheck:
  initialDelay: 180
